[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mapmycode"
version = "1.0.1"
description = "Analyzes python codebases and generates documentation with dependency graphs"
authors = [
    { name = "Saurav Pattnaik" },
    { name = "Jayant Pal" },
]
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "python-dotenv==1.2.2",
    "groq==1.1.2",
    "ipython>=9.11.0",
    "matplotlib==3.10.8",
    "pillow==12.2.0",
    "requests==2.33.1",
    "build>=1.4.0",
    "twine>=6.2.0",
    "langchain-core==1.2.28",
    "pipreqs>=0.4.13",
    "pydantic==2.12.5",
    "networkx>=3.6.1",
    "tiktoken>=0.13.0",
]

[project.scripts]
mapmycode = "mapmycode.cli:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["mapmycode*"]
